
#-------------------------------
# Site Settings
title: 
logo: images/Website Logo BEC V2.png
logo_dark: "/images/Website Logo BEC V2 - Dark.png"
description: Portfolio of Bayley Camp — Designer & Multidisciplinary Creative.
color_scheme: auto

#-------------------------------
# Navigation Settings
menu_settings:
  menu_items:
    - title: 'Home'
      url: '/'
    - title: 'Projects'
      url: '/projects/'
    - title: 'Blog'
      url: '/blog/'
    - title: 'About'
      url: '/about/'

# Call to action button
cta_button:
  enable: true
  cta_button_link: "/contact/"
  cta_button_text: Say Hello!

#-------------------------------
# Author Settings
author:
  author_intro: Hey, I’m Bayley Camp
  author_name: Bayley Camp
  author_role: a Designer and Multidisciplinary Creative
  author_avatar: images/Headshot.jpg

#-------------------------------
# Sidebar Section Settings
sidebar:
  sidebar_title: >
    <span style="font-size: 0.9rem; font-style: italic;">
      A collection of moments and ideas
      from interfaces to imagery, sketches to stories.
    </span>

  sidebar_description: >
    <span style="font-size: 0.9rem; font-style: italic;">
      This is where I share what inspires me and how I bring creativity to life across mediums.
    </span>

# Social Links
social:
  - {icon: "fa-brands fa-linkedin", name: "LinkedIn", link: "https://linkedin.com/in/bayleyecamp"}
  - {icon: "fa-brands fa-pinterest", name: "Pinterest", link: "https://pinterest.com/bcamp_99"}
  - {icon: "fa-brands fa-instagram", name: "Instagram", link: "https://instagram.com/becwrit.99"}

#-------------------------------
# Projects Settings
projects:
  enable: true
  projects_title: Product Design <em>Showcase</em>
  projects_description: I present my top-tier projects, meticulously crafted with unwavering passion, simplicity, boundless creativity, and unparalleled attention to detail.

#-------------------------------
# Blog Section Settings
blog:
  enable: true
  blog_title: Latest <em>Articles</em> & <em>Publications</em>
  blog_description: Discover the latest industry news, insights, and trends in a few clicks.

#-------------------------------
# Testimonials Settings
testimonials:
  enable: false
  testimonials_title: ""
  testimonials_description: ""

testimonial-items: []

#-------------------------------
# Faq (Frequently asked questions) Settings
faq:
  enable: false
  faq_title: ""
  faq_description: ""
  faq_items: []

#-------------------------------
# Newsletter Settings
mailchimp:
  enable: false
  mailchimp_title: ""
  mailchimp_description: ""
  mailchimp_identifier: ""
  mailchimp_input_text: ""
  mailchimp_button_text: ""

#-------------------------------
# Contact Settings
contact:
  email: xovyvdrp
  description: You can reach me directly through this contact form — messages are sent securely and go straight to my inbox.

#-------------------------------
# Comment Section (Disqus)
disqus-identifier: anvod-studio-test

#-------------------------------
# Google Analytics
google-analytics: